custombucket = "bucket-for-pgp"
table = "intellipaat"
databasehost = "database-pgp.cixixytyimq2.us-west-2.rds.amazonaws.com"
duser = "admin"
dpass = "admin123"
s3database = "intellipaat"
kapp = "http://10.10.2.238:30310/"
